Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,16 +1,55 @@
 workflows:
   ios-workflow:
-    name: iOS Build Workflow
+    name: iOS Workflow
+    max_build_duration: 120
+    instance_type: mac_mini_m2
+    integrations:
+      app_store_connect: Codemagic
     environment:
-      vars:
-        BUNDLE_ID: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
-      node: latest
+      ios_signing:
+        distribution_type: app_store
+        bundle_identifier: com.jbpaladinpatriotsclock.jbpaladinpatriotsclock
     scripts:
-      - name: Install Cordova
-        script: npm install -g cordova
+      - name: Install npm dependencies
+        script: | 
+          npm install
+          npm ci
+      - name: Install CocoaPods
+        script: | 
+          sudo gem install cocoapods  # use the latest version available
+      - name: Clean iOS Platform
+        script: |
+          if [ -d "platforms/ios" ]; then
+              cordova platform remove ios || true
+          fi
       - name: Add iOS Platform
-        script: cordova platform add ios
-      - name: Build iOS
-        script: cordova build ios --release --device
+        script: | 
+          cordova platform add ios --confirm --no-interactive --noresources --save
+      - name: Check for Assets.xcassets
+        script: |
+          if [ -d "platforms/ios/JbPaladinPatriotsClock/Assets.xcassets" ]; then
+            echo "Assets.xcassets folder exists."
+          else
+            echo "Assets.xcassets folder does not exist. Please check the platform setup."
+            exit 1  # Exit with an error code to fail the build
+          fi
+      - name: Update Cordova Plugins
+        script: | 
+          cordova plugin update
+      - name: Set Deployment Target for Xcode Compatibility
+        script: |
+          sed -i '' 's/<preference name="deployment-target" value=".*" \/>/<preference name="deployment-target" value="12.0" \/>/' config.xml
+          # Optional: Verify if the target was set correctly
+          grep "<preference name=\"deployment-target\"" config.xml
+      - name: Clean Xcode Derived Data
+        script: |
+          rm -rf ~/Library/Developer/Xcode/DerivedData
+      - name: Set up code signing settings on Xcode project
+        script: | 
+          xcode-project use-profiles  # Set up code signing profiles
+      - name: Build IPA for distribution
+        script: | 
+          cordova build ios --release --device  # Build the iOS app
     artifacts:
-      - build/ios/ipa/*.ipa
+      - platforms/ios/build/device/*.ipa  # Path to the generated IPA file
+      - /tmp/xcodebuild_logs/*.log  # Path to the build logs
